FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app




COPY microservices/repo_embedding /app/microservices/repo_embedding
COPY common /app/common
COPY .env /app/

RUN pip install --no-cache-dir -r /app/microservices/repo_embedding/requirements.txt


# 設置環境變量，確保 Python 找到 common 模塊
ENV PYTHONPATH /app

CMD ["python", "-m", "microservices.repo_embedding.main"]
