import type { Metadata } from "next";
import { ThemeProvider } from "@/lib/providers/theme-provider";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "@/components/layouts/toggle-mode";
import { Toaster } from "@/components/ui/toaster";
import AuthHeader from "@/components/layouts/auth-header/index";
import Header from "@/components/layouts/header";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "42Git",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={font.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {/* TODO: Signin header & Provider*/}
                    <main className="flex flex-col h-screen w-screen p-5">
                        {children}
                    </main>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
